


DEFAULT_BOXES = ((-0.5, -0.5, 0.5, 0.5), (0.2, 0.2, -0.2, -0.2), (-0.8, -0.2, 0.8, 0.2), (-0.2, -0.8, 0.2, 0.8))
NUMBER_DEFAULT_BOXES = len(DEFAULT_BOXES)
NUMBER_CLASSES = 9
NUMBER_CHANNELS = 3
NUMBER_PREDICTIONS = NUMBER_DEFAULT_BOXES * NUMBER_CLASSES
NUMBER_LOCATIONS = NUMBER_DEFAULT_BOXES * 4

#TRAINING
LEARNING_RATE = 1e-4
EPOCHS = 1
BATCH_SIZE = 8
KEEP_PROB = .50

VGG_PATH = os.path.join(data_dir, 'vgg')